#!/usr/bin/env php

<?php

error_reporting(E_ALL|E_STRICT);

require_once(
    __DIR__ . DIRECTORY_SEPARATOR
    . '..' . DIRECTORY_SEPARATOR
    . 'vendor' . DIRECTORY_SEPARATOR
    . 'autoload.php'
);

$parser = new \Symfony\Component\Yaml\Parser();
$config = new \QualityCheck\YmlConfig($parser);
$qc = new \QualityCheck\QualityCheck($config);
$eventDispatcher = \Epa\EventDispatcherFactory::create();
$qc->addObserver($eventDispatcher);
$pluginLoader = new \QualityCheck\PluginLoader($eventDispatcher);
$pluginLoader->loadFromConfig($config);

$qc->build();

?>
